bench:
  workload: ycsb
  record-count: 1000
  read-proportion: 0.95
  update-proportion: 0.05
  scan-proportion: 0
  insert-proportion: 0
  field-num: 10
  field-length: 100
  dist: zipf
  coefficient: 0.5  # 0 as unifrom, 1 as pure zipf

client:
  type: open
  rate: 50000
  max_undone: -1
  forwarding: false
# client: { type: closed, rate: -1, forwarding: false }
n_concurrent: 1
host:
  uiga-server-s-00-r-00: 10.142.0.8
  uiga-server-s-00-r-01: 10.166.0.2
  uiga-server-s-00-r-02: 10.158.0.2
  uiga-server-s-01-r-00: 10.142.0.9
  uiga-server-s-01-r-01: 10.166.0.3
  uiga-server-s-01-r-02: 10.158.0.3
  uiga-server-s-02-r-00: 10.142.0.10
  uiga-server-s-02-r-01: 10.166.0.4
  uiga-server-s-02-r-02: 10.158.0.4
  uiga-proxy-0000: 10.142.0.11
  uiga-proxy-0001: 10.166.0.5
  uiga-proxy-0002: 10.158.0.5
  uiga-proxy-0003: 10.142.0.12
  uiga-proxy-0004: 10.166.0.6
  uiga-proxy-0005: 10.158.0.6
  uiga-proxy-0006: 10.170.0.3
  uiga-proxy-0007: 10.170.0.4
mode: {ab: tiga, batch: false, cc: tiga, ongoing: 1, retry: 20}
process:
  uiga-server-s-00-r-00: uiga-server-s-00-r-00
  uiga-server-s-00-r-01: uiga-server-s-00-r-01
  uiga-server-s-00-r-02: uiga-server-s-00-r-02
  uiga-server-s-01-r-00: uiga-server-s-01-r-00
  uiga-server-s-01-r-01: uiga-server-s-01-r-01
  uiga-server-s-01-r-02: uiga-server-s-01-r-02
  uiga-server-s-02-r-00: uiga-server-s-02-r-00
  uiga-server-s-02-r-01: uiga-server-s-02-r-01
  uiga-server-s-02-r-02: uiga-server-s-02-r-02
  uiga-proxy-0000: uiga-proxy-0000
  uiga-proxy-0001: uiga-proxy-0001
  uiga-proxy-0002: uiga-proxy-0002
  uiga-proxy-0003: uiga-proxy-0003
  uiga-proxy-0004: uiga-proxy-0004
  uiga-proxy-0005: uiga-proxy-0005
  uiga-proxy-0006: uiga-proxy-0006
  uiga-proxy-0007: uiga-proxy-0007
site:
  client:
    -   - uiga-proxy-0000
        - uiga-proxy-0001
        - uiga-proxy-0002
    -   - uiga-proxy-0003
        - uiga-proxy-0004
        - uiga-proxy-0005
    -   - uiga-proxy-0006
        - uiga-proxy-0007
  server: # each line is a partition (i.e., a shard), each line has 3 replicas
    -   - uiga-server-s-00-r-00:10000
        - uiga-server-s-00-r-01:10100
        - uiga-server-s-00-r-02:10200
    -   - uiga-server-s-01-r-01:10400
        - uiga-server-s-01-r-02:10500
        - uiga-server-s-01-r-00:10300
    -   - uiga-server-s-02-r-02:10800
        - uiga-server-s-02-r-00:10600
        - uiga-server-s-02-r-01:10700
  region_server_index:
    -   - 0
        - 1
        - 2
    -   - 2
        - 0
        - 1
    -   - 1
        - 2
        - 0
server_initial_bound:
  - 60000
  - 100000
  - 100000
server_bound_cap:
  - 400000
  - 400000
  - 400000
designate_replica_id:
  - 0
  - 1
  - 2
clockOffset:
  mean: 0
  std: 0
spec_exec: false

preventive: false

nezha-recorder: 127.0.0.1:41237

enable_read_only_optim: false

owd_delta_us: 10000
owd_estimate_percentile: 50
owdDeltaUs: 10000
test_failure_recovery: false
synced_logid_before_failure: 600000
clock_approach: cwcs
